import Texture from '@model/texture.model';

const TEXTURES: Texture[] = [
  new Texture(0, 'Blank'),
  new Texture(1, 'Cobblestone'),
  new Texture(2, 'Dirt'),
  new Texture(3, 'Cobblestone (built)'),
  new Texture(4, 'Wood planks'),
  new Texture(5, 'Sand'),
  new Texture(6, 'Gravel'),
  new Texture(7, 'Gold ore'),
  new Texture(8, 'Iron ore'),
  new Texture(9, 'Wood'),
  new Texture(10, 'Snow'),
  new Texture(11, 'Water'),
  new Texture(12, 'Stone wall'),
  new Texture(13, 'Sandstone'),
  new Texture(14, 'Dark wood'),
  new Texture(15, 'Andesite'),
  new Texture(16, 'Dandelion'),
  new Texture(17, 'Poppy'),
  new Texture(18, 'Mushroom'),
  new Texture(19, 'Red mushrooom'),
  new Texture(20, 'Gold block'),
  new Texture(21, 'Snow block'),
  new Texture(22, 'Stone bricks'),
  new Texture(23, 'Red bricks'),
  new Texture(24, 'TNT'),
  new Texture(25, 'Book shelf'),
  new Texture(26, 'Limestone'),
  new Texture(27, 'Obsidian'),
  new Texture(28, 'Torch'),
  new Texture(29, 'Chest'),
  new Texture(30, 'Ice block'),
  new Texture(31, 'Workbench'),
  new Texture(32, 'Furnace'),
  new Texture(33, 'Stair'),
  new Texture(34, 'Railroad'),
  new Texture(35, 'Redstone torch'),
  new Texture(36, 'Wool'),
  new Texture(37, 'Cactus'),
  new Texture(38, 'Infested stone'),
  new Texture(39, 'Jukebox'),
  new Texture(40, 'Wall torch'),
  new Texture(41, 'Halloween pumpkin'),
  new Texture(42, 'Granite'),
  new Texture(43, 'Soulsand'),
  new Texture(44, 'Glowstone'),
];
export default TEXTURES;
